### ISSUE TITLE
uninitialized constant RRRSpec::Server::StatisticsUpdater::StatisticsUpdaterQueue (NameError)

### ISSUE THREAD

**Issue by mcfiredrill** [cookpad/rrrspec#45]
I get this error when I try to run `rrrspec-server server --config=rrrspec-server-config.rb`.
```
E, [2015-04-24T18:29:28.122808 #25311] ERROR -- : uninitialized constant RRRSpec::Server::StatisticsUpdater::StatisticsUpdaterQueue (NameError)
/Users/tony/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rrrspec-server-0.2.3/lib/rrrspec/server/statistics_updater.rb:17:in `work'
/Users/tony/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rrrspec-server-0.2.3/lib/rrrspec/server/statistics_updater.rb:13:in `block in work_loop'
/Users/tony/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rrrspec-server-0.2.3/lib/rrrspec/server/statistics_updater.rb:13:in `loop'
/Users/tony/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rrrspec-server-0.2.3/lib/rrrspec/server/statistics_updater.rb:13:in `work_loop'
```

My rrrspec-server-config.rb:
```ruby
RRRSpec.configure(:server) do |conf|
  ActiveRecord::Base.default_timezone = :local
  conf.redis = { host: 'localhost', port: 6379 }

  conf.persistence_db = {
    adapter: 'mysql2',
    encoding: 'utf8mb4',
    charset: 'utf8mb4',
    collation: 'utf8mb4_general_ci',
    reconnect: false,
    database: 'rrrspec',
    pool: 5,
    host: 'localhost'
  }
  conf.json_cache_path = './tmp/rrrspec-api-cache'
  conf.execute_log_text_path = "./rrrspec-server-logs"
  conf.pidfile = "./tmp/rrrspec-server.pid"
  conf.daemonize = false
end

RRRSpec.configure(:worker) do |conf|
  conf.redis = { host: 'localhost', port: 6379 }

  conf.rsync_remote_path = 'localhost:/mnt/rrrspec-rsync'
  conf.rsync_options = %w(
    --compress
    --times
    --recursive
    --links
    --perms
    --inplace
    --delete
  ).join(' ')

  conf.working_dir = '/mnt/working'
  conf.worker_type = 'default'
end
```

**Comment by draftcode** [comment]
Did you install rrrspec-client?

**Comment by mcfiredrill** [comment]
Ah yes, looks like I didn't run `bundle` at that time. Sorry! Closing.
